name: Build and Release
on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: gradle:8-jdk17
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Gradle Build
        run: gradle shadowJar

      - name: Release
        uses: GeyserMC/actions/release@master
        with:
          files: | # Newline-separated list of files to upload with optional "label:" prefix
            build/libs/LuckLink-*.jar
          appID: ${{ secrets.RELEASE_APP_ID }} # The ID of the GitHub App to manage the release system
          appPrivateKey: ${{ secrets.RELEASE_APP_PK }} # The private key of the GitHub App in PEM format
          saveMetadata: true
          releaseEnabled: true
          discordWebhook: ${{ secrets.DISCORD_WEBHOOK }}
          ghReleaseNotes: true
          releaseName: Build ${tagBase}
          tagIncrement: true
          preRelease: false